version: "3.7"

services:
  server:
    build: .
    init: true
    volumes:
      - ./transport.json:/app/transport.json:ro
      - ./keys.json:/app/keys.json:ro
    ports:
      - 8000:8000
    # environment:
    # B_SECRET: "ChangeThisInProduction!!!"
